from enum import Enum


class AuditEvent(str, Enum):
    USER_LOGIN = "USER_LOGIN"
    USER_LOGOUT = "USER_LOGOUT"

    BANK_ACCOUNT_LINKED = "BANK_ACCOUNT_LINKED"

    PAYMENT_INITIATED = "PAYMENT_INITIATED"
    PAYMENT_COMPLETED = "PAYMENT_COMPLETED"
    PAYMENT_FAILED = "PAYMENT_FAILED"
    PAYMENT_REJECTED = "PAYMENT_REJECTED"

    UPI_PIN_FAILED = "UPI_PIN_FAILED"
    FRAUD_REJECTED = "FRAUD_REJECTED"
